In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [57]:
df=pd.read_csv("int_247_project_data.csv")
print(df.shape)
data=np.array(df)
print(data)
x=data[:,:-1]
y=data[-1]
print(data.shape)


(1398, 16)
[[ 7.12e+01  6.48e+00 -6.07e-01 ...  6.30e-15  5.74e-22  1.00e+00]
 [ 8.01e+01  2.00e+01 -6.10e-01 ... -3.33e-14  4.95e-21  1.00e+00]
 [ 5.27e+01  5.38e+00  5.73e-02 ... -2.81e-16 -2.97e-21  1.00e+00]
 ...
 [ 9.11e+01  8.79e+00  1.87e+00 ...  7.74e-17  3.34e-24  1.00e+00]
 [ 9.16e+01  9.72e+00  2.00e+00 ...  4.10e-17  1.38e-24  1.00e+00]
 [ 9.01e+01  8.16e+00  2.25e+00 ...  9.31e-17  1.27e-24  1.00e+00]]
(1398, 16)


In [58]:
print(len(data[0]),len(data))
#data=np.array(data)
print(data.shape,type(data),type(data[144,7]))

16 1398
(1398, 16) <class 'numpy.ndarray'> <class 'numpy.float64'>


In [60]:
for i in range(x.shape[1]):
    min_=min(x[:,i])
    max_=max(x[:,i])
    x[:,i]=(x[:,i]-min_)/(max_-min_)
    x[:,i]=(x[:,i]-np.mean(x[:,i]))/np.std(x[:,i])

In [72]:
print(any(np.mean(x,axis=0)>0.00001))
print(any(np.std(x,axis=0)>1))
#print(np.mean(x,axis=0))
#print(np.std(x,axis=0))

False
False
[-2.54128303e-16  8.13210570e-17 -4.06605285e-16 -1.21981586e-16
 -1.01651321e-17  2.03302643e-17 -5.08256606e-18 -4.11687851e-16
  2.03302643e-17  0.00000000e+00  0.00000000e+00  2.28715473e-17
 -1.91866869e-16 -2.05843926e-16 -1.87292559e-15]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
